
//Camera RCA
#define WIDTH 85
#define HEIGHT 60
#define MINCAM 12
#define MAXCAM 82
#define WIDTH_REAL (MAXCAM-MINCAM)
#define CENTCAML (WIDTH_REAL/2)
#define CENTCAMR (CENTCAML+1)

//Boost
#define WIDTH_BOOST 36
#define LIMBOOSTL (CENTCAMR - (WIDTH_BOOST/2))
#define LIMBOOSTR (CENTCAML + (WIDTH_BOOST/2))

//Servo
#define CENTRO_SERVO 18518 //FUTABA 18518                 TOWERPRO 18400
#define LIBERDADE_SERVO 320  // FUTABA 320                TOWERPRO 220
#define ESQUERDA_SERVO (CENTRO_SERVO-LIBERDADE_SERVO)
#define DIREITO_SERVO (CENTRO_SERVO+LIBERDADE_SERVO)

//Tracao
#define MAX_PWM_MOTOR 1
#define MIN_PWM_MOTOR 999

//#define DIFERENCIAL_ATIVO TRAVA_ATIVO
//

//#define REG_TRACAO 999 // 700
//#define MIN_TRACAO 900
//#define MAX_TRACAO 700

//#define REG_TRACAO 999//800
//#define MIN_TRACAO 999//900
//#define MAX_TRACAO 999//500

//Processing
#define LINENOW 0
#define REFERENCE CENTCAMR
#define MIN_ERRO 30
#define MAX_ERRO -MIN_ERRO
#define RANGE_ERRO (MAX_ERRO-MIN_ERRO)

#define LINEBOOST 26
//#define TRAVA_ATIVO 22
//#define MIN_DESTRAVA (WIDTH_TRACK-5)
//#define MAX_DESTRAVA (WIDTH_TRACK+5)

//Proporcional Servo

//#define RANGE_SERVO (DIREITO_SERVO-ESQUERDA_SERVO)

